### ISSUE TITLE
not able to be accessed via hostname

### ISSUE THREAD

**Issue by kentxvalentines** [standardnotes/web#503]
I am not able to access the web interface via hostname but can access via IP:Port

below is the error when i try to access via hostname like https://inxxxx.xxxce/notes
![image](https://user-images.githubusercontent.com/68675600/102003039-74fd7880-3d3d-11eb-87a3-47045d60d483.png)

I have the below .env file.
```
RAILS_ENV=development
PORT=3001
WEB_CONCURRENCY=0
RAILS_LOG_TO_STDOUT=true
RAILS_SERVE_STATIC_FILES=true
SECRET_KEY_BASE=53f298bb5bbee757bf76fa74ed0ad9deefd6cdc37ed3c26e12513eb1e9721a22b87afa4770316eaf2b60671d6a6cdb6b1ff14fc2c277c6beded3b9a122e77ec9
APP_HOST=https://inxxxx.xxxce/notes

EXTENSIONS_MANAGER_LOCATION=extensions/extensions-manager/dist/index.html
BATCH_MANAGER_LOCATION=extensions/batch-manager/dist/index.min.html
SF_DEFAULT_SERVER=http://localhost:3000

# Datadog
DATADOG_ENABLED=false

# Development options
DEV_DEFAULT_SYNC_SERVER=https://sync.standardnotes.org
DEV_EXTENSIONS_MANAGER_LOCATION=public/extensions/extensions-manager/dist/index.html
DEV_BATCH_MANAGER_LOCATION=public/extensions/batch-manager/dist/index.min.html
```

below is the docker-compose.yml file
```
version: '3.8'
services:
  app:
    build:
      context: .
    command: start-local
    env_file: .env
    restart: unless-stopped
    ports:
      - ${PORT}:3001
    volumes:
      - .:/app
    networks:
      standardnotes_proxy:
        aliases:
          - web
      web: {}

networks:
  web:
    name: web
  standardnotes_proxy:
    name: standardnotes                                                                                                                                                                                                                                           
```

I am using `docker run -d -p 3001:3001 --env-file=.env standardnotes/web:stable` to run the docker. 

I get the below docker log when trying to access either via hostname or IP address. So I do not think this is the issue. 
```
{"level":"INFO","time":"2020-12-13T04:23:29.592+00:00","message":"Cannot render console from 15.206.226.105! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255","ddsource":["ruby"]}
/usr/local/bundle/gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
{"level":"INFO","time":"2020-12-13T04:23:29.598+00:00","message":"{\"method\":\"GET\",\"path\":\"/notes\",\"format\":\"html\",\"controller\":\"ApplicationController\",\"action\":\"route_not_found\",\"status\":404,\"duration\":0.8,\"view\":0.27,\"dd\":{\"trace_id\":\"0\",\"span_id\":\"0\",\"env\":\"\",\"service\":\"\",\"version\":\"\"},\"ddsource\":[\"ruby\"],\"time\":\"2020-12-13 04:23:29 +0000\",\"params\":{\"controller\":\"application\",\"action\":\"route_not_found\",\"unmatched_route\":\"notes\"},\"level\":\"WARN\"}","ddsource":["ruby"]}
```

Please let me know if there are any other details required.
